name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Download cassandra 4.0-alpha3
      run: cd && wget "https://downloads.apache.org/cassandra/4.0-alpha3/apache-cassandra-4.0-alpha3-bin.tar.gz"

    - name: untar cassandra
      run: cd && tar xvzf apache-cassandra-4.0-alpha3-bin.tar.gz

    - name: enable materialized view
      run: >
        cd
        && cd ./apache-cassandra-4.0-alpha3/conf/
        && sed -i '/enable_materialized_views/d' ./cassandra.yaml
        && sed -i '$ a enable_materialized_views: true' ./cassandra.yaml

    - name: Build with Maven
      run: mvn --batch-mode verify -Pjacoco,perform-integration-test

    - name: Run SonarCloud analysis
      run: >
        mvn --batch-mode -DskipTests sonar:sonar
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=powsybl-ci-github
        -Dsonar.projectKey=com.powsybl:powsybl-network-store
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build Docker image
      if: github.ref == 'refs/heads/master'
      run: >
        mvn --batch-mode deploy -DskipTests -Dmaven.install.skip -Dmaven.deploy.skip -Dpowsybl.docker.deploy
        -Djib.httpTimeout=60000
        -Djib.to.image=docker.io/powsybl/network-store-server
        -Djib.to.auth.username=powsyblci
        -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}

    - name: Broadcast update event
      if: github.ref == 'refs/heads/master'
      uses: geofjamg/broadcast-event@master
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: network_store_updated
